### ISSUE TITLE
Lists notes on one line

### ISSUE THREAD

**Issue by Khwilo** [GochoMugo/remindme#6]
Upon adding **to-do** items, they appear on one line. Expected result is that they each appear on their own line.

**Comment by GochoMugo** [comment]
More information on issue #7

**Comment by GochoMugo** [comment]
While I get this fixed, check out how to use a custom editor here: http://gochomugo.github.io/remindme/configuration/

**Comment by GochoMugo** [comment]
**FIXED IN v0.6.0**

**Comment by Khwilo** [comment]
The fix worked. Thanks man!

**Comment by GochoMugo** [comment]
Thanks for helping making remindme better. :)

## 

Gocho Mugo,
Forfuture LLC

-----Original Message-----
